services:
  turtlesim:
    build:
      context: ./docker
      dockerfile: Dockerfile.turtlesim
    container_name: ros2-turtlesim
    environment:
      - DISPLAY=${DOCKER_DISPLAY}
      - ROS_DISTRO=humble
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./docker/scripts:/ros2_ws/scripts:ro
      # Linux X11 socket (only works on Linux)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "9090:9090"
    stdin_open: true
    tty: true
    command: ["/bin/bash", "/ros2_ws/scripts/launch_turtlesim.sh"]
